### ISSUE TITLE
FileNotFoundError: 'user_data_tiktok.json' not found

### ISSUE THREAD

**Issue by fralapo** [SomethingObvious/tiktok-activity-data-scraper#1]
I encountered an error while trying to run the `tiktok_post_scraper.py` script in the TikTok Activity Data Scraper project. The error message indicates that the file `user_data_tiktok.json` is missing, causing the script to fail.

**Error Details:**  
When running the command:
```bash
python tiktok_post_scraper.py
```
I receive the following error traceback:
```plaintext
Traceback (most recent call last):
  File "C:\Users\lapo\tiktok-activity-data-scraper\tiktok_post_scraper.py", line 208, in <module>
    asyncio.run(run())
  File "C:\Users\lapo\anaconda3\envs\tiktok\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lapo\anaconda3\envs\tiktok\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lapo\anaconda3\envs\tiktok\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\lapo\tiktok-activity-data-scraper\tiktok_post_scraper.py", line 185, in run
    urls, favorite_video_ids = load_urls_and_favorites_from_json("user_data_tiktok.json", 7999)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lapo\tiktok-activity-data-scraper\tiktok_post_scraper.py", line 82, in load_urls_and_favorites_from_json
    with open(file_path, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'user_data_tiktok.json'
```

**Comment by SomethingObvious** [comment]
You need to download your user data from TikTok to be able to scrape it. Here's a guide : https://support.tiktok.com/en/account-and-privacy/personalized-ads-and-data/requesting-your-data. The program will then scrape the last 8000 posts that you have liked, and output the scraped data of all those that are publicly available.

**Comment by SomethingObvious** [comment]
You'll get a folder called TikTok_Data_xxxxxxx and within that you'll find the requisite file.
